import { ContrastThemeId } from '@/types/shopping';

export interface ContrastThemeConfig {
  id: ContrastThemeId;
  name: string;
  shortLabel: string;
  description: string;
  dotColor: string;
  borderDot: string;
  bgPage: string;
  bgStickyHeader: string;
  borderStickyHeader: string;
  bgAccessibility: string;
  borderAccessibility: string;
  titleColor: string;
  accentBar: string;
  bgCard: string;
  borderCard: string;
  textPrimary: string;
  textSecondary: string;
  bgInput: string;
  borderInput: string;
  bgButtonPrimary: string;
  textButtonPrimary: string;
  bgButtonSecondary: string;
  textButtonSecondary: string;
  borderButtonSecondary: string;
}

export const CONTRAST_THEMES: Record<ContrastThemeId, ContrastThemeConfig> = {
  padrao: {
    id: 'padrao',
    name: 'Claro Padrão',
    shortLabel: 'Claro',
    description: 'Fundo claro com alta legibilidade',
    dotColor: '#FFFFFF',
    borderDot: '#94A3B8',
    bgPage: 'bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100',
    bgStickyHeader: 'bg-slate-50/95 dark:bg-slate-950/95 backdrop-blur-md',
    borderStickyHeader: 'border-slate-200/90 dark:border-slate-800/90',
    bgAccessibility: 'bg-transparent text-slate-800 dark:text-slate-100',
    borderAccessibility: 'border-slate-200 dark:border-slate-800',
    titleColor: 'text-emerald-600 dark:text-emerald-400 font-black',
    accentBar: 'bg-emerald-600',
    bgCard: 'bg-white dark:bg-slate-900',
    borderCard: 'border-slate-200 dark:border-slate-800',
    textPrimary: 'text-slate-900 dark:text-white',
    textSecondary: 'text-slate-500 dark:text-slate-400',
    bgInput: 'bg-slate-50 dark:bg-slate-800',
    borderInput: 'border-slate-300 dark:border-slate-700',
    bgButtonPrimary: 'bg-emerald-600 hover:bg-emerald-700',
    textButtonPrimary: 'text-white',
    bgButtonSecondary: 'bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700',
    textButtonSecondary: 'text-slate-700 dark:text-slate-200',
    borderButtonSecondary: 'border-slate-300 dark:border-slate-700',
  },
  'amarelo-preto': {
    id: 'amarelo-preto',
    name: 'Amarelo & Preto',
    shortLabel: 'Amarelo',
    description: 'Preto puro com amarelo ouro de alto contraste',
    dotColor: '#FACC15',
    borderDot: '#000000',
    bgPage: 'bg-black text-yellow-300',
    bgStickyHeader: 'bg-black/95 backdrop-blur-md',
    borderStickyHeader: 'border-yellow-400',
    bgAccessibility: 'bg-transparent text-yellow-300',
    borderAccessibility: 'border-yellow-400/80',
    titleColor: 'text-yellow-400 font-black',
    accentBar: 'bg-yellow-400',
    bgCard: 'bg-zinc-950',
    borderCard: 'border-yellow-400',
    textPrimary: 'text-yellow-200',
    textSecondary: 'text-yellow-400/80',
    bgInput: 'bg-zinc-900',
    borderInput: 'border-yellow-400',
    bgButtonPrimary: 'bg-yellow-400 hover:bg-yellow-300',
    textButtonPrimary: 'text-black font-extrabold',
    bgButtonSecondary: 'bg-zinc-900 hover:bg-zinc-800',
    textButtonSecondary: 'text-yellow-300',
    borderButtonSecondary: 'border-yellow-400',
  },
  'azul-noturno': {
    id: 'azul-noturno',
    name: 'Azul Noturno',
    shortLabel: 'Azul',
    description: 'Azul marinho profundo com ciano elétrico e branco',
    dotColor: '#38BDF8',
    borderDot: '#0A1128',
    bgPage: 'bg-[#060c1d] text-cyan-100',
    bgStickyHeader: 'bg-[#060c1d]/95 backdrop-blur-md',
    borderStickyHeader: 'border-sky-400',
    bgAccessibility: 'bg-transparent text-sky-200',
    borderAccessibility: 'border-sky-500/80',
    titleColor: 'text-cyan-300 font-black',
    accentBar: 'bg-sky-400',
    bgCard: 'bg-[#0d1a3a]',
    borderCard: 'border-sky-400',
    textPrimary: 'text-white',
    textSecondary: 'text-sky-300',
    bgInput: 'bg-[#091228]',
    borderInput: 'border-sky-400',
    bgButtonPrimary: 'bg-sky-500 hover:bg-sky-400',
    textButtonPrimary: 'text-slate-950 font-bold',
    bgButtonSecondary: 'bg-[#10224d] hover:bg-[#162c64]',
    textButtonSecondary: 'text-sky-200',
    borderButtonSecondary: 'border-sky-500',
  },
  'verde-esmeralda': {
    id: 'verde-esmeralda',
    name: 'Verde Floresta',
    shortLabel: 'Verde',
    description: 'Verde escuro profundo com menta brilhante e branco',
    dotColor: '#34D399',
    borderDot: '#052E16',
    bgPage: 'bg-[#031d0d] text-emerald-100',
    bgStickyHeader: 'bg-[#031d0d]/95 backdrop-blur-md',
    borderStickyHeader: 'border-emerald-400',
    bgAccessibility: 'bg-transparent text-emerald-200',
    borderAccessibility: 'border-emerald-400/80',
    titleColor: 'text-emerald-300 font-black',
    accentBar: 'bg-emerald-400',
    bgCard: 'bg-[#073b1d]',
    borderCard: 'border-emerald-400',
    textPrimary: 'text-white',
    textSecondary: 'text-emerald-300',
    bgInput: 'bg-[#042410]',
    borderInput: 'border-emerald-400',
    bgButtonPrimary: 'bg-emerald-500 hover:bg-emerald-400',
    textButtonPrimary: 'text-slate-950 font-bold',
    bgButtonSecondary: 'bg-[#0a4824] hover:bg-[#0d592d]',
    textButtonSecondary: 'text-emerald-200',
    borderButtonSecondary: 'border-emerald-400',
  },
  'preto-branco': {
    id: 'preto-branco',
    name: 'Preto & Branco',
    shortLabel: 'P&B',
    description: 'Preto absoluto e branco puro sem intermediários (21:1 AAA)',
    dotColor: '#FFFFFF',
    borderDot: '#000000',
    bgPage: 'bg-black text-white',
    bgStickyHeader: 'bg-black/95 backdrop-blur-md',
    borderStickyHeader: 'border-white',
    bgAccessibility: 'bg-transparent text-white',
    borderAccessibility: 'border-white',
    titleColor: 'text-white font-black',
    accentBar: 'bg-white',
    bgCard: 'bg-zinc-950',
    borderCard: 'border-2 border-white',
    textPrimary: 'text-white',
    textSecondary: 'text-zinc-300',
    bgInput: 'bg-zinc-900',
    borderInput: 'border-2 border-white',
    bgButtonPrimary: 'bg-white hover:bg-zinc-200 text-black',
    textButtonPrimary: 'text-black font-black',
    bgButtonSecondary: 'bg-zinc-900 hover:bg-zinc-800 text-white',
    textButtonSecondary: 'text-white font-bold',
    borderButtonSecondary: 'border-2 border-white',
  },
  'ambar-dourado': {
    id: 'ambar-dourado',
    name: 'Âmbar & Ouro',
    shortLabel: 'Âmbar',
    description: 'Preto chocolate com âmbar dourado de alto brilho',
    dotColor: '#F59E0B',
    borderDot: '#78350F',
    bgPage: 'bg-[#180d02] text-amber-100',
    bgStickyHeader: 'bg-[#180d02]/95 backdrop-blur-md',
    borderStickyHeader: 'border-amber-400',
    bgAccessibility: 'bg-transparent text-amber-200',
    borderAccessibility: 'border-amber-400/80',
    titleColor: 'text-amber-400 font-black',
    accentBar: 'bg-amber-400',
    bgCard: 'bg-[#2a1705]',
    borderCard: 'border-amber-400',
    textPrimary: 'text-amber-100',
    textSecondary: 'text-amber-300/80',
    bgInput: 'bg-[#1c0f03]',
    borderInput: 'border-amber-400',
    bgButtonPrimary: 'bg-amber-400 hover:bg-amber-300 text-black',
    textButtonPrimary: 'text-black font-extrabold',
    bgButtonSecondary: 'bg-[#381f08] hover:bg-[#48280a]',
    textButtonSecondary: 'text-amber-200 font-bold',
    borderButtonSecondary: 'border-amber-400',
  },
  'magenta-neon': {
    id: 'magenta-neon',
    name: 'Magenta Neon',
    shortLabel: 'Magenta',
    description: 'Fundo escuro profundo com rosa choque e magenta vivo',
    dotColor: '#F43F5E',
    borderDot: '#881337',
    bgPage: 'bg-[#160413] text-pink-100',
    bgStickyHeader: 'bg-[#160413]/95 backdrop-blur-md',
    borderStickyHeader: 'border-pink-400',
    bgAccessibility: 'bg-transparent text-pink-200',
    borderAccessibility: 'border-pink-400/80',
    titleColor: 'text-pink-400 font-black',
    accentBar: 'bg-pink-400',
    bgCard: 'bg-[#2c0a27]',
    borderCard: 'border-pink-400',
    textPrimary: 'text-pink-100',
    textSecondary: 'text-pink-300/80',
    bgInput: 'bg-[#1c0618]',
    borderInput: 'border-pink-400',
    bgButtonPrimary: 'bg-pink-500 hover:bg-pink-400 text-white',
    textButtonPrimary: 'text-white font-extrabold',
    bgButtonSecondary: 'bg-[#3b0d34] hover:bg-[#4d1144]',
    textButtonSecondary: 'text-pink-200 font-bold',
    borderButtonSecondary: 'border-pink-400',
  },
  'roxo-eletrico': {
    id: 'roxo-eletrico',
    name: 'Roxo Elétrico',
    shortLabel: 'Roxo',
    description: 'Púrpura escuro profundo com lavanda luminosa',
    dotColor: '#A855F7',
    borderDot: '#581C87',
    bgPage: 'bg-[#0f061f] text-purple-100',
    bgStickyHeader: 'bg-[#0f061f]/95 backdrop-blur-md',
    borderStickyHeader: 'border-purple-400',
    bgAccessibility: 'bg-transparent text-purple-200',
    borderAccessibility: 'border-purple-400/80',
    titleColor: 'text-purple-300 font-black',
    accentBar: 'bg-purple-400',
    bgCard: 'bg-[#220e44]',
    borderCard: 'border-purple-400',
    textPrimary: 'text-purple-100',
    textSecondary: 'text-purple-300/80',
    bgInput: 'bg-[#140828]',
    borderInput: 'border-purple-400',
    bgButtonPrimary: 'bg-purple-500 hover:bg-purple-400 text-white',
    textButtonPrimary: 'text-white font-bold',
    bgButtonSecondary: 'bg-[#2e135c] hover:bg-[#3d197a]',
    textButtonSecondary: 'text-purple-200 font-bold',
    borderButtonSecondary: 'border-purple-400',
  },
  'laranja-solar': {
    id: 'laranja-solar',
    name: 'Laranja Segurança',
    shortLabel: 'Laranja',
    description: 'Fundo preto carvão com laranja neon hipervisível',
    dotColor: '#FB923C',
    borderDot: '#7C2D12',
    bgPage: 'bg-[#140a04] text-orange-100',
    bgStickyHeader: 'bg-[#140a04]/95 backdrop-blur-md',
    borderStickyHeader: 'border-orange-400',
    bgAccessibility: 'bg-transparent text-orange-200',
    borderAccessibility: 'border-orange-400/80',
    titleColor: 'text-orange-400 font-black',
    accentBar: 'bg-orange-400',
    bgCard: 'bg-[#2c1709]',
    borderCard: 'border-orange-400',
    textPrimary: 'text-orange-100',
    textSecondary: 'text-orange-300/80',
    bgInput: 'bg-[#180c05]',
    borderInput: 'border-orange-400',
    bgButtonPrimary: 'bg-orange-500 hover:bg-orange-400 text-black',
    textButtonPrimary: 'text-black font-extrabold',
    bgButtonSecondary: 'bg-[#3b1f0c] hover:bg-[#4d2910]',
    textButtonSecondary: 'text-orange-200 font-bold',
    borderButtonSecondary: 'border-orange-400',
  },
  'solar-creme': {
    id: 'solar-creme',
    name: 'Solar & Creme',
    shortLabel: 'Creme',
    description: 'Fundo creme suave e texto marrom escuro de alta leitura',
    dotColor: '#FEF08A',
    borderDot: '#78350F',
    bgPage: 'bg-[#FEFCE8] text-[#451A03]',
    bgStickyHeader: 'bg-[#FEFCE8]/95 backdrop-blur-md',
    borderStickyHeader: 'border-amber-700',
    bgAccessibility: 'bg-transparent text-[#451A03]',
    borderAccessibility: 'border-amber-700/80',
    titleColor: 'text-[#92400E] font-black',
    accentBar: 'bg-[#B45309]',
    bgCard: 'bg-[#FFFDF0]',
    borderCard: 'border-2 border-amber-700',
    textPrimary: 'text-[#451A03]',
    textSecondary: 'text-[#78350F]',
    bgInput: 'bg-white',
    borderInput: 'border-2 border-amber-700',
    bgButtonPrimary: 'bg-[#B45309] hover:bg-[#92400E] text-white',
    textButtonPrimary: 'text-white font-extrabold',
    bgButtonSecondary: 'bg-[#FEF3C7] hover:bg-[#FDE68A] text-[#78350F]',
    textButtonSecondary: 'text-[#78350F] font-bold',
    borderButtonSecondary: 'border-2 border-amber-700',
  },
  'ciano-neon': {
    id: 'ciano-neon',
    name: 'Ciano Neon',
    shortLabel: 'Ciano',
    description: 'Fundo preto carvão com ciano elétrico de altíssimo contraste',
    dotColor: '#06B6D4',
    borderDot: '#083344',
    bgPage: 'bg-[#040d12] text-cyan-100',
    bgStickyHeader: 'bg-[#040d12]/95 backdrop-blur-md',
    borderStickyHeader: 'border-cyan-400',
    bgAccessibility: 'bg-transparent text-cyan-200',
    borderAccessibility: 'border-cyan-400/80',
    titleColor: 'text-cyan-300 font-black',
    accentBar: 'bg-cyan-400',
    bgCard: 'bg-[#0b1f2a]',
    borderCard: 'border-cyan-400',
    textPrimary: 'text-cyan-100',
    textSecondary: 'text-cyan-300/80',
    bgInput: 'bg-[#07151e]',
    borderInput: 'border-cyan-400',
    bgButtonPrimary: 'bg-cyan-400 hover:bg-cyan-300 text-black',
    textButtonPrimary: 'text-black font-extrabold',
    bgButtonSecondary: 'bg-[#102c3c] hover:bg-[#163a4f]',
    textButtonSecondary: 'text-cyan-200 font-bold',
    borderButtonSecondary: 'border-cyan-400',
  },
  'verde-lima': {
    id: 'verde-lima',
    name: 'Verde Lima Neon',
    shortLabel: 'Lima',
    description: 'Preto puro com verde lima fluorescente de máxima visibilidade',
    dotColor: '#A3E635',
    borderDot: '#1A2E05',
    bgPage: 'bg-[#070e03] text-lime-100',
    bgStickyHeader: 'bg-[#070e03]/95 backdrop-blur-md',
    borderStickyHeader: 'border-lime-400',
    bgAccessibility: 'bg-transparent text-lime-200',
    borderAccessibility: 'border-lime-400/80',
    titleColor: 'text-lime-400 font-black',
    accentBar: 'bg-lime-400',
    bgCard: 'bg-[#142609]',
    borderCard: 'border-lime-400',
    textPrimary: 'text-lime-100',
    textSecondary: 'text-lime-300/80',
    bgInput: 'bg-[#0b1604]',
    borderInput: 'border-lime-400',
    bgButtonPrimary: 'bg-lime-400 hover:bg-lime-300 text-black',
    textButtonPrimary: 'text-black font-extrabold',
    bgButtonSecondary: 'bg-[#1c350d] hover:bg-[#254612]',
    textButtonSecondary: 'text-lime-200 font-bold',
    borderButtonSecondary: 'border-lime-400',
  },
  'azul-indigo': {
    id: 'azul-indigo',
    name: 'Azul Índigo Tech',
    shortLabel: 'Índigo',
    description: 'Índigo vibrante moderno padrão Stripe e GitHub',
    dotColor: '#6366F1',
    borderDot: '#312E81',
    bgPage: 'bg-[#0B0F19] text-indigo-100',
    bgStickyHeader: 'bg-[#0B0F19]/95 backdrop-blur-md',
    borderStickyHeader: 'border-indigo-500',
    bgAccessibility: 'bg-transparent text-indigo-200',
    borderAccessibility: 'border-indigo-500/80',
    titleColor: 'text-indigo-400 font-black',
    accentBar: 'bg-indigo-500',
    bgCard: 'bg-[#131B2E]',
    borderCard: 'border-indigo-500/80',
    textPrimary: 'text-white',
    textSecondary: 'text-indigo-300',
    bgInput: 'bg-[#0E1524]',
    borderInput: 'border-indigo-500',
    bgButtonPrimary: 'bg-indigo-600 hover:bg-indigo-500 text-white font-bold',
    textButtonPrimary: 'text-white font-bold',
    bgButtonSecondary: 'bg-[#1A2540] hover:bg-[#233256]',
    textButtonSecondary: 'text-indigo-200 font-bold',
    borderButtonSecondary: 'border-indigo-500',
  },
  'grafite-ardosia': {
    id: 'grafite-ardosia',
    name: 'Grafite Ardósia Pro',
    shortLabel: 'Grafite',
    description: 'Ardósia escura minimalista padrão Linear e VS Code',
    dotColor: '#475569',
    borderDot: '#0F172A',
    bgPage: 'bg-[#0F172A] text-slate-100',
    bgStickyHeader: 'bg-[#0F172A]/95 backdrop-blur-md',
    borderStickyHeader: 'border-slate-500',
    bgAccessibility: 'bg-transparent text-slate-200',
    borderAccessibility: 'border-slate-500/80',
    titleColor: 'text-slate-200 font-black',
    accentBar: 'bg-slate-400',
    bgCard: 'bg-[#1E293B]',
    borderCard: 'border-slate-600',
    textPrimary: 'text-white',
    textSecondary: 'text-slate-300',
    bgInput: 'bg-[#152033]',
    borderInput: 'border-slate-500',
    bgButtonPrimary: 'bg-slate-200 hover:bg-white text-slate-950 font-bold',
    textButtonPrimary: 'text-slate-950 font-bold',
    bgButtonSecondary: 'bg-[#283852] hover:bg-[#334666]',
    textButtonSecondary: 'text-slate-200 font-bold',
    borderButtonSecondary: 'border-slate-500',
  },
  'azul-safira': {
    id: 'azul-safira',
    name: 'Azul Safira Corporativo',
    shortLabel: 'Safira',
    description: 'Azul corporativo profissional padrão LinkedIn e Salesforce',
    dotColor: '#2563EB',
    borderDot: '#1E3A8A',
    bgPage: 'bg-[#071329] text-blue-100',
    bgStickyHeader: 'bg-[#071329]/95 backdrop-blur-md',
    borderStickyHeader: 'border-blue-500',
    bgAccessibility: 'bg-transparent text-blue-200',
    borderAccessibility: 'border-blue-500/80',
    titleColor: 'text-blue-400 font-black',
    accentBar: 'bg-blue-500',
    bgCard: 'bg-[#0F2247]',
    borderCard: 'border-blue-500',
    textPrimary: 'text-white',
    textSecondary: 'text-blue-300',
    bgInput: 'bg-[#0B1A36]',
    borderInput: 'border-blue-500',
    bgButtonPrimary: 'bg-blue-600 hover:bg-blue-500 text-white font-bold',
    textButtonPrimary: 'text-white font-bold',
    bgButtonSecondary: 'bg-[#163163] hover:bg-[#1D3E7D]',
    textButtonSecondary: 'text-blue-200 font-bold',
    borderButtonSecondary: 'border-blue-500',
  },
  'verde-teal': {
    id: 'verde-teal',
    name: 'Verde Menta Teal',
    shortLabel: 'Teal',
    description: 'Menta tecnológico moderno padrão Spotify e Fintechs',
    dotColor: '#14B8A6',
    borderDot: '#134E4A',
    bgPage: 'bg-[#041716] text-teal-100',
    bgStickyHeader: 'bg-[#041716]/95 backdrop-blur-md',
    borderStickyHeader: 'border-teal-400',
    bgAccessibility: 'bg-transparent text-teal-200',
    borderAccessibility: 'border-teal-400/80',
    titleColor: 'text-teal-300 font-black',
    accentBar: 'bg-teal-400',
    bgCard: 'bg-[#082E2B]',
    borderCard: 'border-teal-400',
    textPrimary: 'text-white',
    textSecondary: 'text-teal-300',
    bgInput: 'bg-[#06211F]',
    borderInput: 'border-teal-400',
    bgButtonPrimary: 'bg-teal-500 hover:bg-teal-400 text-slate-950 font-bold',
    textButtonPrimary: 'text-slate-950 font-bold',
    bgButtonSecondary: 'bg-[#0F423E] hover:bg-[#145651]',
    textButtonSecondary: 'text-teal-200 font-bold',
    borderButtonSecondary: 'border-teal-400',
  },
  'vermelho-coral': {
    id: 'vermelho-coral',
    name: 'Vermelho Coral Pro',
    shortLabel: 'Coral',
    description: 'Coral vibrante sofisticado padrão Airbnb e Netflix',
    dotColor: '#EF4444',
    borderDot: '#7F1D1D',
    bgPage: 'bg-[#180606] text-rose-100',
    bgStickyHeader: 'bg-[#180606]/95 backdrop-blur-md',
    borderStickyHeader: 'border-red-500',
    bgAccessibility: 'bg-transparent text-rose-200',
    borderAccessibility: 'border-red-500/80',
    titleColor: 'text-red-400 font-black',
    accentBar: 'bg-red-500',
    bgCard: 'bg-[#2D0C0C]',
    borderCard: 'border-red-500',
    textPrimary: 'text-white',
    textSecondary: 'text-rose-300',
    bgInput: 'bg-[#210909]',
    borderInput: 'border-red-500',
    bgButtonPrimary: 'bg-red-600 hover:bg-red-500 text-white font-bold',
    textButtonPrimary: 'text-white font-bold',
    bgButtonSecondary: 'bg-[#421414] hover:bg-[#571B1B]',
    textButtonSecondary: 'text-rose-200 font-bold',
    borderButtonSecondary: 'border-red-500',
  },
  'fucsia-pro': {
    id: 'fucsia-pro',
    name: 'Fúcsia Glamour',
    shortLabel: 'Fúcsia',
    description: 'Fúcsia magenta sofisticado padrão Instagram e Lyft',
    dotColor: '#D946EF',
    borderDot: '#701A75',
    bgPage: 'bg-[#160418] text-fuchsia-100',
    bgStickyHeader: 'bg-[#160418]/95 backdrop-blur-md',
    borderStickyHeader: 'border-fuchsia-500',
    bgAccessibility: 'bg-transparent text-fuchsia-200',
    borderAccessibility: 'border-fuchsia-500/80',
    titleColor: 'text-fuchsia-400 font-black',
    accentBar: 'bg-fuchsia-500',
    bgCard: 'bg-[#2B0A2F]',
    borderCard: 'border-fuchsia-500',
    textPrimary: 'text-white',
    textSecondary: 'text-fuchsia-300',
    bgInput: 'bg-[#1F0722]',
    borderInput: 'border-fuchsia-500',
    bgButtonPrimary: 'bg-fuchsia-600 hover:bg-fuchsia-500 text-white font-bold',
    textButtonPrimary: 'text-white font-bold',
    bgButtonSecondary: 'bg-[#3F1145] hover:bg-[#52175A]',
    textButtonSecondary: 'text-fuchsia-200 font-bold',
    borderButtonSecondary: 'border-fuchsia-500',
  },
  'ouro-nordico': {
    id: 'ouro-nordico',
    name: 'Ouro Nórdico',
    shortLabel: 'Ouro',
    description: 'Ouro rico luxuoso de alto contraste padrão FinTech premium',
    dotColor: '#EAB308',
    borderDot: '#713F12',
    bgPage: 'bg-[#141004] text-yellow-100',
    bgStickyHeader: 'bg-[#141004]/95 backdrop-blur-md',
    borderStickyHeader: 'border-yellow-500',
    bgAccessibility: 'bg-transparent text-yellow-200',
    borderAccessibility: 'border-yellow-500/80',
    titleColor: 'text-yellow-400 font-black',
    accentBar: 'bg-yellow-500',
    bgCard: 'bg-[#261E0A]',
    borderCard: 'border-yellow-500',
    textPrimary: 'text-white',
    textSecondary: 'text-yellow-300',
    bgInput: 'bg-[#1C1607]',
    borderInput: 'border-yellow-500',
    bgButtonPrimary: 'bg-yellow-500 hover:bg-yellow-400 text-slate-950 font-extrabold',
    textButtonPrimary: 'text-slate-950 font-extrabold',
    bgButtonSecondary: 'bg-[#382C0E] hover:bg-[#4A3B14]',
    textButtonSecondary: 'text-yellow-200 font-bold',
    borderButtonSecondary: 'border-yellow-500',
  },
  'azul-celeste': {
    id: 'azul-celeste',
    name: 'Azul Celeste',
    shortLabel: 'Celeste',
    description: 'Azul céu elétrico padrão Twitter/X e Telegram',
    dotColor: '#0284C7',
    borderDot: '#0C4A6E',
    bgPage: 'bg-[#03111C] text-sky-100',
    bgStickyHeader: 'bg-[#03111C]/95 backdrop-blur-md',
    borderStickyHeader: 'border-sky-400',
    bgAccessibility: 'bg-transparent text-sky-200',
    borderAccessibility: 'border-sky-400/80',
    titleColor: 'text-sky-300 font-black',
    accentBar: 'bg-sky-400',
    bgCard: 'bg-[#082238]',
    borderCard: 'border-sky-400',
    textPrimary: 'text-white',
    textSecondary: 'text-sky-300',
    bgInput: 'bg-[#05192A]',
    borderInput: 'border-sky-400',
    bgButtonPrimary: 'bg-sky-500 hover:bg-sky-400 text-slate-950 font-bold',
    textButtonPrimary: 'text-slate-950 font-bold',
    bgButtonSecondary: 'bg-[#0E3352] hover:bg-[#13436B]',
    textButtonSecondary: 'text-sky-200 font-bold',
    borderButtonSecondary: 'border-sky-400',
  },
  'vinho-bordeaux': {
    id: 'vinho-bordeaux',
    name: 'Vinho Bordeaux',
    shortLabel: 'Vinho',
    description: 'Bordeaux nobre profundo padrão Notion e apps editoriais',
    dotColor: '#9F1239',
    borderDot: '#4C0519',
    bgPage: 'bg-[#140308] text-rose-100',
    bgStickyHeader: 'bg-[#140308]/95 backdrop-blur-md',
    borderStickyHeader: 'border-rose-500',
    bgAccessibility: 'bg-transparent text-rose-200',
    borderAccessibility: 'border-rose-500/80',
    titleColor: 'text-rose-300 font-black',
    accentBar: 'bg-rose-500',
    bgCard: 'bg-[#290812]',
    borderCard: 'border-rose-500',
    textPrimary: 'text-white',
    textSecondary: 'text-rose-300',
    bgInput: 'bg-[#1C050D]',
    borderInput: 'border-rose-500',
    bgButtonPrimary: 'bg-rose-600 hover:bg-rose-500 text-white font-bold',
    textButtonPrimary: 'text-white font-bold',
    bgButtonSecondary: 'bg-[#3D0D1C] hover:bg-[#4E1225]',
    textButtonSecondary: 'text-rose-200 font-bold',
    borderButtonSecondary: 'border-rose-500',
  },
  'verde-oliva': {
    id: 'verde-oliva',
    name: 'Verde Oliva Nature',
    shortLabel: 'Oliva',
    description: 'Oliva orgânica suave padrão Medium e Substack',
    dotColor: '#65A30D',
    borderDot: '#1A2E05',
    bgPage: 'bg-[#0A1104] text-lime-100',
    bgStickyHeader: 'bg-[#0A1104]/95 backdrop-blur-md',
    borderStickyHeader: 'border-lime-500',
    bgAccessibility: 'bg-transparent text-lime-200',
    borderAccessibility: 'border-lime-500/80',
    titleColor: 'text-lime-300 font-black',
    accentBar: 'bg-lime-500',
    bgCard: 'bg-[#16220A]',
    borderCard: 'border-lime-500',
    textPrimary: 'text-white',
    textSecondary: 'text-lime-300',
    bgInput: 'bg-[#0F1907]',
    borderInput: 'border-lime-500',
    bgButtonPrimary: 'bg-lime-600 hover:bg-lime-500 text-slate-950 font-bold',
    textButtonPrimary: 'text-slate-950 font-bold',
    bgButtonSecondary: 'bg-[#223311] hover:bg-[#2C4217]',
    textButtonSecondary: 'text-lime-200 font-bold',
    borderButtonSecondary: 'border-lime-500',
  },
  'terracota-rust': {
    id: 'terracota-rust',
    name: 'Terracota Rust',
    shortLabel: 'Terracota',
    description: 'Argila aquecida elegante padrão Basecamp e Notion',
    dotColor: '#C2410C',
    borderDot: '#431407',
    bgPage: 'bg-[#140804] text-orange-100',
    bgStickyHeader: 'bg-[#140804]/95 backdrop-blur-md',
    borderStickyHeader: 'border-orange-500',
    bgAccessibility: 'bg-transparent text-orange-200',
    borderAccessibility: 'border-orange-500/80',
    titleColor: 'text-orange-400 font-black',
    accentBar: 'bg-orange-500',
    bgCard: 'bg-[#28120A]',
    borderCard: 'border-orange-500',
    textPrimary: 'text-white',
    textSecondary: 'text-orange-300',
    bgInput: 'bg-[#1C0D07]',
    borderInput: 'border-orange-500',
    bgButtonPrimary: 'bg-orange-600 hover:bg-orange-500 text-white font-bold',
    textButtonPrimary: 'text-white font-bold',
    bgButtonSecondary: 'bg-[#3B1B10] hover:bg-[#4E2416]',
    textButtonSecondary: 'text-orange-200 font-bold',
    borderButtonSecondary: 'border-orange-500',
  },
  'platina-minimal': {
    id: 'platina-minimal',
    name: 'Platina Minimalista',
    shortLabel: 'Platina',
    description: 'Fundo claro moderno padrão Apple iOS e macOS',
    dotColor: '#94A3B8',
    borderDot: '#475569',
    bgPage: 'bg-[#F8FAFC] text-slate-900',
    bgStickyHeader: 'bg-[#F8FAFC]/95 backdrop-blur-md',
    borderStickyHeader: 'border-slate-300',
    bgAccessibility: 'bg-transparent text-slate-800',
    borderAccessibility: 'border-slate-300',
    titleColor: 'text-slate-900 font-black',
    accentBar: 'bg-slate-700',
    bgCard: 'bg-white',
    borderCard: 'border-slate-300 shadow-sm',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    bgInput: 'bg-slate-50',
    borderInput: 'border-slate-400',
    bgButtonPrimary: 'bg-slate-900 hover:bg-slate-800 text-white font-bold',
    textButtonPrimary: 'text-white font-bold',
    bgButtonSecondary: 'bg-slate-200 hover:bg-slate-300 text-slate-800',
    textButtonSecondary: 'text-slate-800 font-bold',
    borderButtonSecondary: 'border-slate-300',
  },
  'turquesa-oceano': {
    id: 'turquesa-oceano',
    name: 'Turquesa Oceano',
    shortLabel: 'Turquesa',
    description: 'Turquesa oceânico moderno padrão DigitalOcean e Cloud UI',
    dotColor: '#0D9488',
    borderDot: '#042F2E',
    bgPage: 'bg-[#021314] text-teal-100',
    bgStickyHeader: 'bg-[#021314]/95 backdrop-blur-md',
    borderStickyHeader: 'border-teal-400',
    bgAccessibility: 'bg-transparent text-teal-200',
    borderAccessibility: 'border-teal-400/80',
    titleColor: 'text-teal-300 font-black',
    accentBar: 'bg-teal-400',
    bgCard: 'bg-[#072628]',
    borderCard: 'border-teal-400',
    textPrimary: 'text-white',
    textSecondary: 'text-teal-300',
    bgInput: 'bg-[#041C1E]',
    borderInput: 'border-teal-400',
    bgButtonPrimary: 'bg-teal-500 hover:bg-teal-400 text-slate-950 font-bold',
    textButtonPrimary: 'text-slate-950 font-bold',
    bgButtonSecondary: 'bg-[#0C373A] hover:bg-[#11484C]',
    textButtonSecondary: 'text-teal-200 font-bold',
    borderButtonSecondary: 'border-teal-400',
  },
};

export const THEME_LIST = Object.values(CONTRAST_THEMES);
