import { ContrastThemeId } from '@/types/shopping';

export interface ContrastThemeConfig {
  id: ContrastThemeId;
  name: string;
  shortLabel: string;
  description: string;
  dotColor: string;
  borderDot: string;
  bgPage: string;
  bgStickyHeader: string;
  borderStickyHeader: string;
  bgAccessibility: string;
  borderAccessibility: string;
  titleColor: string;
  accentBar: string;
  bgCard: string;
  borderCard: string;
  textPrimary: string;
  textSecondary: string;
  bgInput: string;
  borderInput: string;
  bgButtonPrimary: string;
  textButtonPrimary: string;
  bgButtonSecondary: string;
  textButtonSecondary: string;
  borderButtonSecondary: string;
}

export const CONTRAST_THEMES: Record<ContrastThemeId, ContrastThemeConfig> = {
  padrao: {
    id: 'padrao',
    name: 'Claro Padrão',
    shortLabel: 'Claro',
    description: 'Fundo claro com alta legibilidade',
    dotColor: '#FFFFFF',
    borderDot: '#94A3B8',
    bgPage: 'bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100',
    bgStickyHeader: 'bg-slate-50/95 dark:bg-slate-950/95 backdrop-blur-md',
    borderStickyHeader: 'border-slate-200/90 dark:border-slate-800/90',
    bgAccessibility: 'bg-transparent text-slate-800 dark:text-slate-100',
    borderAccessibility: 'border-slate-200 dark:border-slate-800',
    titleColor: 'text-emerald-600 dark:text-emerald-400 font-black',
    accentBar: 'bg-emerald-600',
    bgCard: 'bg-white dark:bg-slate-900',
    borderCard: 'border-slate-200 dark:border-slate-800',
    textPrimary: 'text-slate-900 dark:text-white',
    textSecondary: 'text-slate-500 dark:text-slate-400',
    bgInput: 'bg-slate-50 dark:bg-slate-800',
    borderInput: 'border-slate-300 dark:border-slate-700',
    bgButtonPrimary: 'bg-emerald-600 hover:bg-emerald-700',
    textButtonPrimary: 'text-white',
    bgButtonSecondary: 'bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700',
    textButtonSecondary: 'text-slate-700 dark:text-slate-200',
    borderButtonSecondary: 'border-slate-300 dark:border-slate-700',
  },
  'amarelo-preto': {
    id: 'amarelo-preto',
    name: 'Amarelo & Preto',
    shortLabel: 'Amarelo',
    description: 'Preto puro com amarelo ouro de alto contraste',
    dotColor: '#FACC15',
    borderDot: '#000000',
    bgPage: 'bg-black text-yellow-300',
    bgStickyHeader: 'bg-black/95 backdrop-blur-md',
    borderStickyHeader: 'border-yellow-400',
    bgAccessibility: 'bg-transparent text-yellow-300',
    borderAccessibility: 'border-yellow-400/80',
    titleColor: 'text-yellow-400 font-black',
    accentBar: 'bg-yellow-400',
    bgCard: 'bg-zinc-950',
    borderCard: 'border-yellow-400',
    textPrimary: 'text-yellow-200',
    textSecondary: 'text-yellow-400/80',
    bgInput: 'bg-zinc-900',
    borderInput: 'border-yellow-400',
    bgButtonPrimary: 'bg-yellow-400 hover:bg-yellow-300',
    textButtonPrimary: 'text-black font-extrabold',
    bgButtonSecondary: 'bg-zinc-900 hover:bg-zinc-800',
    textButtonSecondary: 'text-yellow-300',
    borderButtonSecondary: 'border-yellow-400',
  },
  'azul-noturno': {
    id: 'azul-noturno',
    name: 'Azul Noturno',
    shortLabel: 'Azul',
    description: 'Azul marinho profundo com ciano elétrico e branco',
    dotColor: '#38BDF8',
    borderDot: '#0A1128',
    bgPage: 'bg-[#060c1d] text-cyan-100',
    bgStickyHeader: 'bg-[#060c1d]/95 backdrop-blur-md',
    borderStickyHeader: 'border-sky-400',
    bgAccessibility: 'bg-transparent text-sky-200',
    borderAccessibility: 'border-sky-500/80',
    titleColor: 'text-cyan-300 font-black',
    accentBar: 'bg-sky-400',
    bgCard: 'bg-[#0d1a3a]',
    borderCard: 'border-sky-400',
    textPrimary: 'text-white',
    textSecondary: 'text-sky-300',
    bgInput: 'bg-[#091228]',
    borderInput: 'border-sky-400',
    bgButtonPrimary: 'bg-sky-500 hover:bg-sky-400',
    textButtonPrimary: 'text-slate-950 font-bold',
    bgButtonSecondary: 'bg-[#10224d] hover:bg-[#162c64]',
    textButtonSecondary: 'text-sky-200',
    borderButtonSecondary: 'border-sky-500',
  },
  'verde-esmeralda': {
    id: 'verde-esmeralda',
    name: 'Verde Floresta',
    shortLabel: 'Verde',
    description: 'Verde escuro profundo com menta brilhante e branco',
    dotColor: '#34D399',
    borderDot: '#052E16',
    bgPage: 'bg-[#031d0d] text-emerald-100',
    bgStickyHeader: 'bg-[#031d0d]/95 backdrop-blur-md',
    borderStickyHeader: 'border-emerald-400',
    bgAccessibility: 'bg-transparent text-emerald-200',
    borderAccessibility: 'border-emerald-400/80',
    titleColor: 'text-emerald-300 font-black',
    accentBar: 'bg-emerald-400',
    bgCard: 'bg-[#073b1d]',
    borderCard: 'border-emerald-400',
    textPrimary: 'text-white',
    textSecondary: 'text-emerald-300',
    bgInput: 'bg-[#042410]',
    borderInput: 'border-emerald-400',
    bgButtonPrimary: 'bg-emerald-500 hover:bg-emerald-400',
    textButtonPrimary: 'text-slate-950 font-bold',
    bgButtonSecondary: 'bg-[#0a4824] hover:bg-[#0d592d]',
    textButtonSecondary: 'text-emerald-200',
    borderButtonSecondary: 'border-emerald-400',
  },
  'preto-branco': {
    id: 'preto-branco',
    name: 'Preto & Branco',
    shortLabel: 'P&B',
    description: 'Preto absoluto e branco puro sem intermediários (21:1 AAA)',
    dotColor: '#FFFFFF',
    borderDot: '#000000',
    bgPage: 'bg-black text-white',
    bgStickyHeader: 'bg-black/95 backdrop-blur-md',
    borderStickyHeader: 'border-white',
    bgAccessibility: 'bg-transparent text-white',
    borderAccessibility: 'border-white',
    titleColor: 'text-white font-black',
    accentBar: 'bg-white',
    bgCard: 'bg-zinc-950',
    borderCard: 'border-2 border-white',
    textPrimary: 'text-white',
    textSecondary: 'text-zinc-300',
    bgInput: 'bg-zinc-900',
    borderInput: 'border-2 border-white',
    bgButtonPrimary: 'bg-white hover:bg-zinc-200 text-black',
    textButtonPrimary: 'text-black font-black',
    bgButtonSecondary: 'bg-zinc-900 hover:bg-zinc-800 text-white',
    textButtonSecondary: 'text-white font-bold',
    borderButtonSecondary: 'border-2 border-white',
  },
  'ambar-dourado': {
    id: 'ambar-dourado',
    name: 'Âmbar & Ouro',
    shortLabel: 'Âmbar',
    description: 'Preto chocolate com âmbar dourado de alto brilho',
    dotColor: '#F59E0B',
    borderDot: '#78350F',
    bgPage: 'bg-[#180d02] text-amber-100',
    bgStickyHeader: 'bg-[#180d02]/95 backdrop-blur-md',
    borderStickyHeader: 'border-amber-400',
    bgAccessibility: 'bg-transparent text-amber-200',
    borderAccessibility: 'border-amber-400/80',
    titleColor: 'text-amber-400 font-black',
    accentBar: 'bg-amber-400',
    bgCard: 'bg-[#2a1705]',
    borderCard: 'border-amber-400',
    textPrimary: 'text-amber-100',
    textSecondary: 'text-amber-300/80',
    bgInput: 'bg-[#1c0f03]',
    borderInput: 'border-amber-400',
    bgButtonPrimary: 'bg-amber-400 hover:bg-amber-300 text-black',
    textButtonPrimary: 'text-black font-extrabold',
    bgButtonSecondary: 'bg-[#381f08] hover:bg-[#48280a]',
    textButtonSecondary: 'text-amber-200 font-bold',
    borderButtonSecondary: 'border-amber-400',
  },
  'magenta-neon': {
    id: 'magenta-neon',
    name: 'Magenta Neon',
    shortLabel: 'Magenta',
    description: 'Fundo escuro profundo com rosa choque e magenta vivo',
    dotColor: '#F43F5E',
    borderDot: '#881337',
    bgPage: 'bg-[#160413] text-pink-100',
    bgStickyHeader: 'bg-[#160413]/95 backdrop-blur-md',
    borderStickyHeader: 'border-pink-400',
    bgAccessibility: 'bg-transparent text-pink-200',
    borderAccessibility: 'border-pink-400/80',
    titleColor: 'text-pink-400 font-black',
    accentBar: 'bg-pink-400',
    bgCard: 'bg-[#2c0a27]',
    borderCard: 'border-pink-400',
    textPrimary: 'text-pink-100',
    textSecondary: 'text-pink-300/80',
    bgInput: 'bg-[#1c0618]',
    borderInput: 'border-pink-400',
    bgButtonPrimary: 'bg-pink-500 hover:bg-pink-400 text-white',
    textButtonPrimary: 'text-white font-extrabold',
    bgButtonSecondary: 'bg-[#3b0d34] hover:bg-[#4d1144]',
    textButtonSecondary: 'text-pink-200 font-bold',
    borderButtonSecondary: 'border-pink-400',
  },
  'roxo-eletrico': {
    id: 'roxo-eletrico',
    name: 'Roxo Elétrico',
    shortLabel: 'Roxo',
    description: 'Púrpura escuro profundo com lavanda luminosa',
    dotColor: '#A855F7',
    borderDot: '#581C87',
    bgPage: 'bg-[#0f061f] text-purple-100',
    bgStickyHeader: 'bg-[#0f061f]/95 backdrop-blur-md',
    borderStickyHeader: 'border-purple-400',
    bgAccessibility: 'bg-transparent text-purple-200',
    borderAccessibility: 'border-purple-400/80',
    titleColor: 'text-purple-300 font-black',
    accentBar: 'bg-purple-400',
    bgCard: 'bg-[#220e44]',
    borderCard: 'border-purple-400',
    textPrimary: 'text-purple-100',
    textSecondary: 'text-purple-300/80',
    bgInput: 'bg-[#140828]',
    borderInput: 'border-purple-400',
    bgButtonPrimary: 'bg-purple-500 hover:bg-purple-400 text-white',
    textButtonPrimary: 'text-white font-bold',
    bgButtonSecondary: 'bg-[#2e135c] hover:bg-[#3d197a]',
    textButtonSecondary: 'text-purple-200 font-bold',
    borderButtonSecondary: 'border-purple-400',
  },
  'laranja-solar': {
    id: 'laranja-solar',
    name: 'Laranja Segurança',
    shortLabel: 'Laranja',
    description: 'Fundo preto carvão com laranja neon hipervisível',
    dotColor: '#FB923C',
    borderDot: '#7C2D12',
    bgPage: 'bg-[#140a04] text-orange-100',
    bgStickyHeader: 'bg-[#140a04]/95 backdrop-blur-md',
    borderStickyHeader: 'border-orange-400',
    bgAccessibility: 'bg-transparent text-orange-200',
    borderAccessibility: 'border-orange-400/80',
    titleColor: 'text-orange-400 font-black',
    accentBar: 'bg-orange-400',
    bgCard: 'bg-[#2c1709]',
    borderCard: 'border-orange-400',
    textPrimary: 'text-orange-100',
    textSecondary: 'text-orange-300/80',
    bgInput: 'bg-[#180c05]',
    borderInput: 'border-orange-400',
    bgButtonPrimary: 'bg-orange-500 hover:bg-orange-400 text-black',
    textButtonPrimary: 'text-black font-extrabold',
    bgButtonSecondary: 'bg-[#3b1f0c] hover:bg-[#4d2910]',
    textButtonSecondary: 'text-orange-200 font-bold',
    borderButtonSecondary: 'border-orange-400',
  },
  'solar-creme': {
    id: 'solar-creme',
    name: 'Solar & Creme',
    shortLabel: 'Creme',
    description: 'Fundo creme suave e texto marrom escuro de alta leitura',
    dotColor: '#FEF08A',
    borderDot: '#78350F',
    bgPage: 'bg-[#FEFCE8] text-[#451A03]',
    bgStickyHeader: 'bg-[#FEFCE8]/95 backdrop-blur-md',
    borderStickyHeader: 'border-amber-700',
    bgAccessibility: 'bg-transparent text-[#451A03]',
    borderAccessibility: 'border-amber-700/80',
    titleColor: 'text-[#92400E] font-black',
    accentBar: 'bg-[#B45309]',
    bgCard: 'bg-[#FFFDF0]',
    borderCard: 'border-2 border-amber-700',
    textPrimary: 'text-[#451A03]',
    textSecondary: 'text-[#78350F]',
    bgInput: 'bg-white',
    borderInput: 'border-2 border-amber-700',
    bgButtonPrimary: 'bg-[#B45309] hover:bg-[#92400E] text-white',
    textButtonPrimary: 'text-white font-extrabold',
    bgButtonSecondary: 'bg-[#FEF3C7] hover:bg-[#FDE68A] text-[#78350F]',
    textButtonSecondary: 'text-[#78350F] font-bold',
    borderButtonSecondary: 'border-2 border-amber-700',
  },
  'ciano-neon': {
    id: 'ciano-neon',
    name: 'Ciano Neon',
    shortLabel: 'Ciano',
    description: 'Fundo preto carvão com ciano elétrico de altíssimo contraste',
    dotColor: '#06B6D4',
    borderDot: '#083344',
    bgPage: 'bg-[#040d12] text-cyan-100',
    bgStickyHeader: 'bg-[#040d12]/95 backdrop-blur-md',
    borderStickyHeader: 'border-cyan-400',
    bgAccessibility: 'bg-transparent text-cyan-200',
    borderAccessibility: 'border-cyan-400/80',
    titleColor: 'text-cyan-300 font-black',
    accentBar: 'bg-cyan-400',
    bgCard: 'bg-[#0b1f2a]',
    borderCard: 'border-cyan-400',
    textPrimary: 'text-cyan-100',
    textSecondary: 'text-cyan-300/80',
    bgInput: 'bg-[#07151e]',
    borderInput: 'border-cyan-400',
    bgButtonPrimary: 'bg-cyan-400 hover:bg-cyan-300 text-black',
    textButtonPrimary: 'text-black font-extrabold',
    bgButtonSecondary: 'bg-[#102c3c] hover:bg-[#163a4f]',
    textButtonSecondary: 'text-cyan-200 font-bold',
    borderButtonSecondary: 'border-cyan-400',
  },
  'verde-lima': {
    id: 'verde-lima',
    name: 'Verde Lima Neon',
    shortLabel: 'Lima',
    description: 'Preto puro com verde lima fluorescente de máxima visibilidade',
    dotColor: '#A3E635',
    borderDot: '#1A2E05',
    bgPage: 'bg-[#070e03] text-lime-100',
    bgStickyHeader: 'bg-[#070e03]/95 backdrop-blur-md',
    borderStickyHeader: 'border-lime-400',
    bgAccessibility: 'bg-transparent text-lime-200',
    borderAccessibility: 'border-lime-400/80',
    titleColor: 'text-lime-400 font-black',
    accentBar: 'bg-lime-400',
    bgCard: 'bg-[#142609]',
    borderCard: 'border-lime-400',
    textPrimary: 'text-lime-100',
    textSecondary: 'text-lime-300/80',
    bgInput: 'bg-[#0b1604]',
    borderInput: 'border-lime-400',
    bgButtonPrimary: 'bg-lime-400 hover:bg-lime-300 text-black',
    textButtonPrimary: 'text-black font-extrabold',
    bgButtonSecondary: 'bg-[#1c350d] hover:bg-[#254612]',
    textButtonSecondary: 'text-lime-200 font-bold',
    borderButtonSecondary: 'border-lime-400',
  },
};

export const THEME_LIST = Object.values(CONTRAST_THEMES);
